### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by NoisyAstronomer** [WellDoneCode/google--notifications-remover#1]
Using Chrome Version 43.0.2357.81 (64-bit) on Mac OS X 10.10.3 (several machines) and the extension is no longer blocking the notifications on Gmail, Google Calendar, and other Google pages. Started a few days ago (exact date unknown.) No other changes to my browser or OS have been made, so maybe an update on Google's end? 

Thanks!

**Comment by abelozerov** [comment]
Fixed, thank you very much for notification
